### ISSUE TITLE
 No module named 'stacked_capsule_autoencoders'

### ISSUE THREAD

**Issue by Ab26** [akosiorek/stacked_capsule_autoencoders#4]
I have installed all the dependencies as mentioned in the README.md and all requirements mentioned in requirement.txt also satisfies, but it is still giving following error :

/home/Abhishek/.local/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "train.py", line 33, in <module>
    from stacked_capsule_autoencoders.capsules.configs import data_config
ModuleNotFoundError: No module named 'stacked_capsule_autoencoders'

I also tried running from the google-research-master folder but the error is persistent.

**Comment by akosiorek** [comment]
Judging by the error message, it looks like the `pandas` module has a problem with a module called `lzma` and therefore cannot be imported, which further prevents importing `stacked_capsule_autoencoders` module. I'd suggest looking into `pandas` and why it doesn't work for you.
