### ISSUE TITLE
no "normalized_sobel_edges"

### ISSUE THREAD

**Issue by Add2seconds** [akosiorek/stacked_capsule_autoencoders#8]
> stacked_capsule_autoencoders\capsules\models\scae.py

line 158
```
if prep == 'sobel':
    img = preprocess.normalized_sobel_edges(img)
```
but there is no "normalized_sobel_edges" in 

> stacked_capsule_autoencoders\capsules\data\preprocess.py

**Comment by akosiorek** [comment]
Thanks, I've just added the method.

**Comment by Add2seconds** [comment]
Thank you for you reply

The code you just submitted

> stacked_capsule_autoencoders\capsules\data\preprocess.py

line 114

`  sobel_img = abs(sobel_img - contrib_distributions.percentile`

I guess it should be:
tf.contrib.distributions.percentile

**Comment by akosiorek** [comment]
Right, that's correct. I'd encourage using code from https://github.com/google-research/google-research/tree/master/stacked_capsule_autoencoders as this repo is not maintained.
